---
# Basic playbook that installed powerline and copies the configuration file

- name: Install Powerline.
  hosts: all                        # Change this to your inventory groups (or leave all)
  gather_facts: false               # Faster execution since we don't need to gather facts

  tasks:
    - name: Ensure powerline packages are installed.
      ansible.builtin.apt:          # Fedora: use ansible.builtin.dnf (or both can use ansible.builtin.package)
        name: powerline
        state: present
      become: true
    
    # Copy the configuration file to the home directory of the ansible user.
    - name: Ensure ~/.bash_aliases is copied.
      ansible.builtin.copy:
        src: bash_aliases
        dest: ~/.bash_aliases       # Fedora: use ~/.bashrc.d/bash_aliases
        owner: alvin
        group: alvin
        mode: '0664'